### ISSUE TITLE
Show only nodes in context menu search

### ISSUE THREAD

**Issue by MaxTretikov** [darkshapes/singularity#15]
Showing the directory structure should be an opt-in feature rather than the default or only.

**Comment by exdysa** [comment]
its very unorganized as it is right now. comfy didnt really think the node organization through, and as a result i cant find anything because it shows me folders, rather than node results. I also dont know why it wants to draw a box around the nodes rather than the folders, this is also very confusing. im slowed from doing my work with this.

**Comment by exdysa** [comment]
i fixed the boxes, i might try to generate the menu myself tomorrow

**Comment by exdysa** [comment]
im the best, man, i diiiid it
