### ISSUE TITLE
Bind ctrl-click drag to box select

### ISSUE THREAD

**Issue by MaxTretikov** [darkshapes/singularity#16]

**Comment by exdysa** [comment]
i like shift-left click multi-select node as it is right now, i feel like it should have been this way from the start, but our users will expect ctrl-drag coming from comfy. so we must accomodate. technically this makes it broken since the user will think it so when it doesnt work. i dont remember why we needed it to be ctrl-shift tho? ought to be just ctrl click-drag

**Comment by exdysa** [comment]
I don't think this can be done and I no longer care about it.
