### ISSUE TITLE
Move 'trash' element

### ISSUE THREAD

**Issue by MaxTretikov** [darkshapes/singularity#17]
My only objection is that the node preview shows up in the bottom right, but it shouldn't matter because it would literally be impossible to hit the trash button while having your mouse over a node as well as being extremely impractical. Would the user get confused by having a preview in the "trash area" or trash in the "node preview area"?

**Comment by exdysa** [comment]
> My only objection is that the node preview shows up in the bottom right, but it shouldn't matter because it would literally be impossible to hit the trash button while having your mouse over a node as well as being extremely impractical. Would the user get confused by having a preview in the "trash area" or trash in the "node preview area"?

well.. we definitely dont want these two functions interfering with each other's operation, like clicking the node preview and accidentally clearing the graph, but the delete cannot be where it is right now because its simply too easy to hit. from a UX perspective the state of it atm is 100% broken.

i would suggest the best thing would be to take it off of the main graph completely and put it IN the left side panel for workflow loading. its not something that is likely to be used as often as, say, the node list, or the queue list.


it could be a slide-in menu at the bottom with a small tab indicating its presence and that might be okay, but i almost never use this function so i feel like it isnt important enough for main view visbility.

**Comment by exdysa** [comment]
i changed my mind!!!
