### ISSUE TITLE
Convert node parameters to inputs and back through right click

### ISSUE THREAD

**Issue by MaxTretikov** [darkshapes/singularity#6]

**Comment by exdysa** [comment]
![Image](https://github.com/MaxTretikov/SabreUI/assets/91800957/b4c3231b-54bb-4c8c-a6c6-62b1ae40c837)
![Image](https://github.com/MaxTretikov/SabreUI/assets/91800957/b20db6bf-a878-4fd0-b077-e07b4f8b2b87)

**Comment by exdysa** [comment]
the top image is an input, the bottom image is a widget. in classic you are able to switch back and forth with an option in a right click against the node. this is core functionality that does not work in sabre & is absolutely essential for operation, i would consider it high priority since it is used for about every workflow i can think of
